### ISSUE TITLE
cron job not running

### ISSUE THREAD

**Issue by JediBrooker** [nextcloud/previewgenerator#104]
i create the cron job but i get an error saying that the script can only be run from command line only. any advice?

**Comment by rullzer** [comment]
What is the cronjob you created?

**Comment by stratege1401** [comment]
hate those people asking for help and been away for more than 4 months !!!

**Comment by danger89** [comment]
yes kill them xD

**Comment by MichaIng** [comment]
@stratege1401 
Probably because the first reaction on this issue was two months later, a time range where most users already forgot about it, found another solution or moved to other software 😉.

**Comment by joshtrichards** [comment]
Closing due to:

- age
- insufficient information provided to look into (actual error, actual cron entry)
- no follow-up 

If further help is needed, I suggest the help forum - https://help.nextcloud.com, but don't hesitate to follow-up if you think there's still some sort of actual bug here in the app.
