### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by futuremd85** [nextcloud/previewgenerator#207]
Recreating post from almost a year ago. User had different resolution.

Tried running ./occ preview:generate-all -vvv but received Command not found error. Tried running in nextcloud directory as nextcloud user to no avail. Looking at occ file, there seems to be no mention as to where to find the commands. My code is not strong, so I may be wrong about this. 

occ contents below, what else would you like to see?

#!/usr/bin/env php
<?php
/**
 * Copyright (c) 2013 Thomas Müller <thomas.mueller@tmit.eu>
 * This file is licensed under the Affero General Public License version 3 or
 * later.
 * See the COPYING-README file.
 */

//$argv = $_SERVER['argv'];
require_once __DIR__ . '/console.php';

Someone please help. I used this on a previous installation of nextcloud and loved it! I need it back for my sanity.

**Comment by MichaIng** [comment]
Since this is a support request and no bug report, generally you should ask something like this on the forum: https://help.nextcloud.com/

But since I'm here now:
1. How is your Nextcloud installed, which distribution or appliance?
2. Where is your Nextcloud install directory located?
3. Which user runs your webserver and PHP?

On a "regular" Debian/Ubuntu/Raspbian install with Nextcloud at `/var/www/nextcloud` and webserver + PHP running as user `www-data` and `sudo` available, the command would be this:
```
sudo -u www-data php /var/www/nextcloud/occ preview:generate-all -vvv
```

**Comment by st3iny** [comment]
I'm closing this issue because it is stale.
