### ISSUE TITLE
preview generation fails：missing: "file"

### ISSUE THREAD

**Issue by Sssssti** [nextcloud/previewgenerator#438]
After I run the command：sudo -u www php /www/wwwroot/nextcloud/occ preview:generate -vvv

In Input.php line 76:
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Not enough arguments (missing: "file").                 
                                                          

Exception trace:
  at /www/wwwroot/nextcloud/3rdparty/symfony/console/Input/Input.php:76
 Symfony\Component\Console\Input\Input->validate() at /www/wwwroot/nextcloud/3rdparty/symfony/console/Command/Command.php:293
 Symfony\Component\Console\Command\Command->run() at /www/wwwroot/nextcloud/3rdparty/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at /www/wwwroot/nextcloud/3rdparty/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /www/wwwroot/nextcloud/3rdparty/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /www/wwwroot/nextcloud/lib/private/Console/Application.php:211
 OC\Console\Application->run() at /www/wwwroot/nextcloud/console.php:100
 require_once() at /www/wwwroot/nextcloud/occ:11

preview:generate [-s|--size SIZE] [-c|--crop] [-m|--mode MODE] [--] <file>

I don't know what missing files means?...
Preview Generator Version:5.4.0
Nextcloud Version:27.1.4

**Comment by st3iny** [comment]
This is not a command of this app. The following commands are provided by the previewgenerator app.

## Commands

### preview:generate-all [--path=PATH ...] [user_id ...]

Loop over all files and try to generate previews for them. If one or multiple user ids are supplied
it will just loop over the files of those users. You can also limit the generation to one or more
paths using `--path="/[username]/files/[folder path]"`, e.g. `--path="/alice/files/Photos"`. Note that
all given user_ids are ignored if at least one path is specified.

### preview:pre-generate

Do the actual pregeneration. This means only for new or modified files (since
the app was enabled or the last pregeneration was done).
